#!/usr/bin/env bash

APPPILOT_OK=0
APPPILOT_ERR_GENERIC=1
APPPILOT_ERR_ARGS=2
APPPILOT_ERR_APP_NOT_FOUND=3
APPPILOT_ERR_MISSING_DEP=4
APPPILOT_ERR_PERMISSION=5
APPPILOT_ERR_CONFIG=6
APPPILOT_ERR_UNSUPPORTED=7
APPPILOT_ERR_HEALTH=8
APPPILOT_ERR_LOCKED=9
